## Import

In [1]:
import pandas as pd
import numpy as np

# Regression model
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

# Regression ensemble
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import VotingRegressor


from sklearn.multiclass import OneVsRestClassifier

# Class model
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

# Class ensemble
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier


# Modol Select
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

# Metric
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score

# Joblib
from joblib import dump

# Math
from itertools import product
from math import sqrt

# Api
import requests
from dotenv import load_dotenv
import os
import csv
import time

## Preproc

In [5]:
df = pd.read_csv("data/epi_r.csv")
df.drop_duplicates(subset=['title',], keep='first', inplace=True)
df.drop(columns="Unnamed: 0", inplace=True)

df.to_csv("data/epi_r.csv")

In [ ]:
def open_df():
    df = pd.read_csv("data/epi_r.csv")

    df = df.drop(
        columns=[
            "title",
            "#cakeweek",
            "#wasteless",
            "22-minute meals",
            "3-ingredient recipes",
            "30 days of groceries",
            "advance prep required",
            "alabama",
            "alaska",
            "alcoholic",
            "anniversary",
            "anthony bourdain",
            "aperitif",
            "appetizer",
            "arizona",
            "aspen",
            "atlanta",
            "australia",
            "back to school",
            "backyard bbq",
            "bake",
            "bastille day",
            "beverly hills",
            "birthday",
            "bitters",
            "blender",
            "boil",
            "bon appétit",
            "bon app��tit",
            "boston",
            "braise",
            "broil",
            "brooklyn",
            "brownie",
            "brunch",
            "buffet",
            "bulgaria",
            "burrito",
            "cake",
            "california",
            "cambridge",
            "camping",
            "canada",
            "candy thermometer",
            "casserole/gratin",
            "cheese",
            "chicago",
            "chili",
            "chill",
            "christmas",
            "christmas eve",
            "cinco de mayo",
            "cobbler/crumble",
            "cocktail",
            "cocktail party",
            "coffee grinder",
            "colorado",
            "columbus",
            "condiment",
            "condiment/spread",
            "connecticut",
            "cook like a diner",
            "cookbook critic",
            "cookie",
            "cookies",
            "costa mesa",
            "cranberry sauce",
            "cupcake",
            "dairy",
            "dairy free",
            "dallas",
            "deep-fry",
            "denver",
            "dessert",
            "digestif",
            "dinner",
            "dip",
            "diwali",
            "dominican republic",
            "dorie greenspan",
            "double boiler",
            "drink",
            "drinks",
            "easter",
            "edible gift",
            "egypt",
            "emeril lagasse",
            "engagement party",
            "england",
            "entertaining",
            "epi + ushg",
            "epi loves the microwave",
            "fall",
            "family reunion",
            "fat free",
            "father's day",
            "flaming hot summer",
            "flat bread",
            "florida",
            "food processor",
            "fourth of july",
            "france",
            "frankenrecipe",
            "freeze/chill",
            "freezer food",
            "friendsgiving",
            "frittata",
            "fritter",
            "frozen dessert",
            # 'fruit'
            "fry",
            "game",
            "georgia",
            "germany",
            "gourmet",
            "graduation",
            "grains",
            "grill",
            "grill/barbecue",
            "halloween",
            "hamburger",
            "hanukkah",
            "harpercollins",
            "hawaii",
            "healdsburg",
            "healthy",
            "high fiber",
            "hollywood",
            "hors d'oeuvre",
            "house & garden",
            "house cocktail",
            "houston",
            "ice cream",
            "ice cream machine",
            "idaho",
            "illinois",
            "indiana",
            "iowa",
            "ireland",
            "israel",
            "italy",
            "jam or jelly",
            "jamaica",
            "japan",
            "juicer",
            "kansas",
            "kansas city",
            "kentucky",
            "kentucky derby",
            "kid-friendly",
            "kidney friendly",
            "kitchen olympics",
            "kosher",
            "kosher for passover",
            "kwanzaa",
            "labor day",
            "lancaster",
            "las vegas",
            "lasagna",
            "leftovers",
            "london",
            "long beach",
            "los angeles",
            "louisiana",
            "louisville",
            "low cal",
            "low carb",
            "low cholesterol",
            "low fat",
            "low sodium",
            "low sugar",
            "low/no sugar",
            "lunar new year",
            "lunch",
            "macaroni and cheese",
            "maine",
            "mandoline",
            "mardi gras",
            "marinade",
            "marinate",
            "maryland",
            "massachusetts",
            "meat",
            "meatball",
            "meatloaf",
            "mexico",
            "miami",
            "michigan",
            "microwave",
            "minneapolis",
            "minnesota",
            "mississippi",
            "missouri",
            "mixer",
            "mother's day",
            "muffin",
            "nancy silverton",
            "nebraska",
            "new hampshire",
            "new jersey",
            "new mexico",
            "new orleans",
            "new year's day",
            "new year's eve",
            "new york",
            "no meat, no problem",
            "no sugar added",
            "no-cook",
            "non-alcoholic",
            "north carolina",
            "ohio",
            "oklahoma",
            "oktoberfest",
            "omelet",
            "one-pot meal",
            "orange juice",
            "oregon",
            "organic",
            "oscars",
            "pacific palisades",
            "paleo",
            "pan-fry",
            "pancake",
            "parade",
            "paris",
            "party",
            "pasadena",
            "passover",
            "pasta",
            "pasta maker",
            "pastry",
            "peanut free",
            "pennsylvania",
            "persian new year",
            "peru",
            "pescatarian",
            "philippines",
            "pickles",
            "picnic",
            "pie",
            "pittsburgh",
            "pizza",
            "poker/game night",
            "portland",
            "pot pie",
            "potato salad",
            "potluck",
            "poultry",
            "poultry sausage",
            "pressure cooker",
            "providence",
            "punch",
            "purim",
            "quiche",
            "quick & easy",
            "quick and healthy",
            "ramadan",
            "ramekin",
            "raw",
            "rhode island",
            "roast",
            "rosh hashanah/yom kippur",
            "rub",
            "salad",
            "salad dressing",
            "salsa",
            "san francisco",
            "sandwich",
            "sandwich theory",
            "santa monica",
            "sauce",
            "sausage",
            "sauté",
            "scotch",
            "seafood",
            "seattle",
            "self",
            "shavuot",
            "shellfish",
            "shower",
            "side",
            "simmer",
            "skewer",
            "slow cooker",
            "smoker",
            "smoothie",
            "snack",
            "snack week",
            "sorbet",
            "soufflé/meringue",
            "soup/stew",
            "south carolina",
            "soy free",
            "spain",
            "spirit",
            "spring",
            "spritzer",
            "st. louis",
            "st. patrick's day",
            "steak",
            "steam",
            "stew",
            "stir-fry",
            "stock",
            "stuffing/dressing",
            "sugar conscious",
            "sukkot",
            "summer",
            "super bowl",
            "suzanne goin",
            "switzerland",
            "taco",
            "tailgating",
            "tart",
            "tennessee",
            "tested & improved",
            "texas",
            "thanksgiving",
            "tofu",
            "turkey",
            "utah",
            "valentine's day",
            "vegan",
            "vegetable",
            "vegetarian",
            "vermont",
            "virginia",
            "waffle",
            "washington",
            "washington, d.c.",
            "wedding",
            "weelicious",
            "west virginia",
            "westwood",
            "wheat/gluten-free",
            "whiskey",
            "whole wheat",
            "wine",
            "winter",
            "wisconsin",
            "wok",
            "yonkers",
            "protein",
            "fat",
            "calories",
            "sodium",
            "cookbooks",
            "url"
        ]
    )

    return df


df = open_df()

# print(df.columns.to_list())

In [12]:
df.dropna(inplace=True)

In [ ]:

df

       rating  almond  amaretto  anchovy  ...  yogurt  yuca  zucchini  cookbooks
0       2.500     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
1       4.375     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
2       3.750     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
3       5.000     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
4       3.125     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
...       ...     ...       ...      ...  ...     ...   ...       ...        ...
20047   3.125     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
20048   4.375     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
20049   4.375     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
20050   4.375     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0
20051   4.375     0.0       0.0      0.0  ...     0.0   0.0       0.0        0.0

[20052 rows x 335 columns]

In [ ]:
train, test = train_test_split(
    df,
    test_size=0.2,
    random_state=21,
    # stratify=df['raiting'],
)

X_train = train.drop(columns="rating")
y_train = train[['rating']]

X_test = test.drop(columns='rating')
y_test = test[['rating']]

## Regression model

In [ ]:
model = LinearRegression(
    copy_X=True,
)

param = {
    "fit_intercept": [False, True],
    "positive": [False, True],
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train)

model1 = gs.best_estimator_

y_pred = model1.predict(X_test)

sqrt(mean_squared_error(y_test ,y_pred))

1.279024611391608

In [ ]:
model = DecisionTreeRegressor(
    random_state=21
)

param = {
    "max_depth": list(range(1, 10)),
    "min_samples_split": list(range(2, 5)),
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train)

model2 = gs.best_estimator_

y_pred = model2.predict(X_test)

sqrt(mean_squared_error(y_test ,y_pred))

1.2823416001200567

In [ ]:
model = SVR()

param = {
    "kernel": ["linear", "poly", "rbf", "sigmoid",],
    "epsilon": [0.01, 0.1, 1, 5],
    "gamma": ["scale", "auto"]
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train.squeeze())

model3 = gs.best_estimator_

y_pred = model3.predict(X_test)

sqrt(mean_squared_error(y_test ,y_pred))

/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

1.264559965136313

### Best regression model - SVR

In [20]:
best_reg_model = model3

In [ ]:
y_pred = best_reg_model.predict(X_test)

sqrt(mean_squared_error(y_test ,y_pred))

1.2706619723151378

### Reg ensemble

In [49]:
model = RandomForestRegressor(
    random_state=21
)

param = {
    "n_estimators" : list(range(50, 150, 10)),
    "max_depth" : list(range(2, 8))
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train.squeeze())

model = gs.best_estimator_

y_pred = model.predict(X_test)

sqrt(mean_squared_error(y_test ,y_pred))

1.2677531210982418

In [50]:
model = BaggingRegressor(
    estimator=model1,
)

param = {
    "n_estimators" : list(range(10, 50, 5)),
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train.squeeze())

model = gs.best_estimator_

y_pred = model.predict(X_test)

sqrt(mean_squared_error(y_test ,y_pred))

1.3361263908165089

In [52]:
model = VotingRegressor(
    estimators=[
        ("linreg", model1),
        ("tree", model2),
        ("svr", model3),
        ],
)

param = {
    "weights" : list(product(set(range(1, 5)), set(range(1, 5)), set(range(1, 5)))), 

}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train.squeeze())

model = gs.best_estimator_

y_pred = model.predict(X_test)

(mean_squared_error(y_test ,y_pred)) ** 0.5

ValueError:
All the 320 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
320 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/ensemble/_voting.py", line 678, in fit
    return super().fit(X, y, **fit_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/ensemble/_voting.py", line 80, in fit
    names, clfs = self._validate_estimators()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/ensemble/_base.py", line 243, in _validate_estimators
    raise ValueError(
ValueError: The estimator OneVsRestClassifier should be a regressor.

### Naive predict

In [ ]:
y_test['predict'] = y_test['rating'].mean()

sqrt(mean_squared_error(y_test['predict'], y_test['rating']))

1.3072126305093743

## Classification (6 class)

### Preproc

In [62]:
df = open_df()

df['rating'] = df['rating'].round(0)

df['rating'] = df['rating'].astype('int8')

df

       rating  almond  amaretto  anchovy  ...  yellow squash  yogurt  yuca  zucchini
0           2     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
1           4     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
2           4     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
3           5     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
4           3     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
...       ...     ...       ...      ...  ...            ...     ...   ...       ...
20047       3     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
20048       4     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
20049       4     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
20050       4     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0
20051       4     0.0       0.0      0.0  ...            0.0     0.0   0.0       0.0

[20052 rows x 334 columns]

In [64]:
train, test = train_test_split(
    df,
    test_size=0.2,
    random_state=21,
    stratify=df['rating'],
)

X_train = train.drop(columns="rating")
y_train = train[['rating']]

X_test = test.drop(columns='rating')
y_test = test[['rating']]

In [ ]:
model = OneVsRestClassifier(
    LogisticRegression(
        random_state=21,
        fit_intercept=True
    ),
    n_jobs=-1
)

param = {
    "estimator__C": [0.01, 0.1, 1, 5, 10],
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='accuracy',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train)

model1 = gs.best_estimator_

y_pred = model1.predict(X_test)

accuracy_score(y_test ,y_pred)

0.8164329685571782

In [ ]:
model = OneVsRestClassifier(
    SVC(
    random_state=21,
    ),
    n_jobs=-1
)

param = {
    "estimator__C": [0.01, 0.1, 1, 5, 10],
    "estimator__kernel": ['rbf', 'linear', 'poly', "sigmoid"]
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='accuracy',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train)

model2 = gs.best_estimator_

y_pred = model2.predict(X_test)

accuracy_score(y_test ,y_pred)

0.8164329685571782

In [ ]:
model = OneVsRestClassifier(
    DecisionTreeClassifier(
        random_state=21,
    ),
    n_jobs=-1
)

param = {
    "estimator__max_depth": [2, 3, 4, 5, 6, 7],
    "estimator__min_samples_split": [1, 2, 3, 4, 6]
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='accuracy',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train)

model3 = gs.best_estimator_

y_pred = model3.predict(X_test)

accuracy_score(y_test ,y_pred)

/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:490: FitFailedWarning:
30 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/_utils.py", line 109, in __call__
    return self.func(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/parallel.py", line 607, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 184, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/multiclass.py", line 96, in _fit_binary
    estimator.fit(X, y, **fit_params)
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/base.py", line 1329, in wrapper
    estimator._validate_params()
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/base.py", line 492, in _validate_params
    validate_parameter_constraints(
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/multiclass.py", line 376, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/parallel.py", line 1784, in _retrieve
    self._raise_error_fast()
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/parallel.py", line 1859, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/parallel.py", line 758, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/joblib/parallel.py", line 773, in _return_or_raise
    raise self._result
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_search.py:1137: UserWarning: One or more of the test scores are non-finite: [       nan 0.66280147 0.66280147 0.66280147 0.66280147        nan
 0.6629886  0.6629886  0.6629886  0.6629886         nan 0.66286378
 0.66286378 0.66286378 0.66292612        nan 0.66292618 0.66286384
 0.66305085 0.6629885         nan 0.6632379  0.66311321 0.6632379
 0.66336255        nan 0.66261442 0.66261442 0.66261442 0.66317544]
  warnings.warn(

0.8157328574597609

### 6 Class Ensemble

In [ ]:
model = RandomForestClassifier(
    random_state=21
)

param = {
    "n_estimators" : list(range(50, 150, 10)),
    "max_depth" : list(range(2, 8))
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train.squeeze())

model = gs.best_estimator_

y_pred = model.predict(X_test)

accuracy_score(y_test ,y_pred)

1.3698866300563635

In [ ]:
model = BaggingClassifier(
    estimator=model1,
)

param = {
    "n_estimators" : list(range(10, 50, 5)),
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train.squeeze())

model = gs.best_estimator_

y_pred = model.predict(X_test)

accuracy_score(y_test ,y_pred)

1.344258407327032

In [8]:
model = VotingClassifier(
    estimators=[
        ("linreg", model1),
        ("tree", model2),
        ("svr", model3),
    ],
)

# param = {
#     "weights" : list(product(set(range(1, 5)), set(range(1, 5)), set(range(1, 5)))), 

# }

# gs = GridSearchCV(
#     model,
#     param_grid=param,
#     scoring='neg_mean_squared_error',
#     n_jobs=-1,
#     cv=5
# )

# gs.fit(X_train, y_train.squeeze())

# model = gs.best_estimator_

y_pred = model.predict(X_test)

accuracy_score(y_test ,y_pred)

NameError: name 'model1' is not defined

### 6 class naive

In [74]:
y_test['predict'] = y_test['rating'].mode()[0]

accuracy_score(y_test['predict'], y_test['rating'])

0.6576913487908252

## Classification (3 class)

In [4]:
df = open_df()

df['rating'] = df['rating'].round(0)

df['rating'] = df['rating'].apply(lambda x: 0 if x in (0, 1) else 1 if x in (2, 3) else 2)

# df.drop(columns="rating", inplace=True)

# df.rename(columns={'rating_class': "rating"}, inplace=True)

df

,rating,almond,amaretto,anchovy,anise,apple,apple juice,apricot,artichoke,arugula,...,wasabi,watercress,watermelon,white wine,wild rice,windsor,yellow squash,yogurt,yuca,zucchini
0,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20047,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20048,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20049,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20050,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20051,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
train, test = train_test_split(
    df,
    test_size=0.2,
    random_state=21,
    stratify=df['rating'],
)

X_train = train.drop(columns="rating")
y_train = train[['rating']]

X_test = test.drop(columns='rating')
y_test = test[['rating']]

X_test

,almond,amaretto,anchovy,anise,apple,apple juice,apricot,artichoke,arugula,asian pear,...,wasabi,watercress,watermelon,white wine,wild rice,windsor,yellow squash,yogurt,yuca,zucchini
12026,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8844,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1924,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19982,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8934,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17066,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17405,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18440,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13898,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Model (3 class)

In [9]:
model = OneVsRestClassifier(
    LogisticRegression(
        random_state=21,
        fit_intercept=True
    ),
    n_jobs=-1
)

param = {
    "estimator__C": [0.01, 0.1, 1, 5, 10],
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='accuracy',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train)

model1 = gs.best_estimator_

y_pred = model1.predict(X_test)

accuracy_score(y_test ,y_pred)

0.7978060334081276

In [6]:
model = OneVsRestClassifier(
    SVC(
    random_state=21,
    ),
    n_jobs=-1
)

param = {
    "estimator__C": [0.01, 0.1, 1, 5, 10],
    "estimator__kernel": ['rbf', 'linear', 'poly', "sigmoid"]
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='accuracy',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train)

model2 = gs.best_estimator_

y_pred = model2.predict(X_test)

accuracy_score(y_test ,y_pred)

0.7990526053353278

In [10]:
model = OneVsRestClassifier(
    DecisionTreeClassifier(
        random_state=21,
    ),
    n_jobs=-1
)

param = {
    "estimator__max_depth": [2, 3, 4, 5, 6, 7],
    "estimator__min_samples_split": [1, 2, 3, 4, 6]
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='accuracy',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train)

model3 = gs.best_estimator_

y_pred = model3.predict(X_test)

accuracy_score(y_test ,y_pred)

/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:490: FitFailedWarning:
30 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/_utils.py", line 109, in __call__
    return self.func(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/parallel.py", line 607, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 184, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/multiclass.py", line 96, in _fit_binary
    estimator.fit(X, y, **fit_params)
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/base.py", line 1329, in wrapper
    estimator._validate_params()
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/base.py", line 492, in _validate_params
    validate_parameter_constraints(
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/multiclass.py", line 376, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/parallel.py", line 1784, in _retrieve
    self._raise_error_fast()
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/parallel.py", line 1859, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/parallel.py", line 758, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/joblib/parallel.py", line 773, in _return_or_raise
    raise self._result
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/src/venv/lib/python3.12/site-packages/sklearn/model_selection/_search.py:1137: UserWarning: One or more of the test scores are non-finite: [       nan 0.79870327 0.79870327 0.79870327 0.79870327        nan
 0.79870327 0.79870327 0.79870327 0.79870327        nan 0.79864092
 0.79864092 0.79864092 0.79851625        nan 0.79820455 0.79820455
 0.7982669  0.79820451        nan 0.79633434 0.79633434 0.79639669
 0.79689534        nan 0.79583561 0.79589795 0.79583561 0.79633434]
  warnings.warn(

0.7968087758663674

### Ensemble (3 class)

In [16]:
model = RandomForestClassifier(
    random_state=21
)

param = {
    "n_estimators" : list(range(50, 150, 10)),
    "max_depth" : list(range(2, 8))
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train.squeeze())

model = gs.best_estimator_

y_pred = model.predict(X_test)

accuracy_score(y_test ,y_pred)

0.7943156320119671

In [11]:
model = BaggingClassifier(
    estimator=model1,
)

param = {
    "n_estimators" : list(range(10, 50, 5)),
}

gs = GridSearchCV(
    model,
    param_grid=param,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    cv=5
)

gs.fit(X_train, y_train.squeeze())

model = gs.best_estimator_

y_pred = model.predict(X_test)

accuracy_score(y_test ,y_pred)

/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 579, in mean_squared_error
    _check_reg_targets_with_floating_dtype(
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 208, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, sample_weight, multioutput = _check_reg_targets(
                                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 114, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1022, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 878, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/series.py", line 899, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/arrays/numpy_.py", line 193, in __array__
    result = np.asarray(self._ndarray, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'great'

  warnings.warn(
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 579, in mean_squared_error
    _check_reg_targets_with_floating_dtype(
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 208, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, sample_weight, multioutput = _check_reg_targets(
                                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 114, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1022, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 878, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/series.py", line 899, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/arrays/numpy_.py", line 193, in __array__
    result = np.asarray(self._ndarray, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'so-so'

  warnings.warn(
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 579, in mean_squared_error
    _check_reg_targets_with_floating_dtype(
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 208, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, sample_weight, multioutput = _check_reg_targets(
                                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 114, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1022, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 878, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/series.py", line 899, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/arrays/numpy_.py", line 193, in __array__
    result = np.asarray(self._ndarray, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'so-so'

  warnings.warn(
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 579, in mean_squared_error
    _check_reg_targets_with_floating_dtype(
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 208, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, sample_weight, multioutput = _check_reg_targets(
                                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 114, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1022, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 878, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/series.py", line 899, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/arrays/numpy_.py", line 193, in __array__
    result = np.asarray(self._ndarray, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'so-so'

  warnings.warn(
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 579, in mean_squared_error
    _check_reg_targets_with_floating_dtype(
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 208, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, sample_weight, multioutput = _check_reg_targets(
                                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py", line 114, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1022, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 878, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/series.py", line 899, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/pandas/core/arrays/numpy_.py", line 193, in __array__
    result = np.asarray(self._ndarray, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'so-so'

  warnings.warn(
/Users/ambem1/Desktop/school21/DSB12_Food_nutrition.ID_1577655-Team_TL_atalantd.60177fe6_91cf_4c37-1/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):

0.7980553477935677

In [12]:
model = VotingClassifier(
    estimators=[
        ("linreg", model1),
        ("tree", model2),
        ("svr", model3),
    ],
)

# param = {
#     # "weights" : list(product(set(range(1, 5)), set(range(1, 5)), set(range(1, 5)))), 

# }

# gs = GridSearchCV(
#     model,
#     param_grid=param,
#     scoring='neg_mean_squared_error',
#     n_jobs=-1,
#     cv=5
# )

model.fit(X_train, y_train.squeeze())

# model = gs.best_estimator_

y_pred = model.predict(X_test)

accuracy_score(y_test ,y_pred)

0.7980553477935677

### Class 3 naive

In [6]:
y_test['predict'] = y_test['rating'].mode()[0]

accuracy_score(y_test['predict'], y_test['rating'])

0.7933183744702069

## Decision

Best model is SVC

In [13]:
dump(model, "model.joblib")

['model.joblib']

## API

In [ ]:
def get_api_key ():
    load_dotenv()
    api_key = os.getenv('API_KEY')
    if not api_key:
        raise ValueError('No api key found')
    print(api_key)
    return api_key

def request_food(ingridients):
    url = f"https://api.nal.usda.gov/fdc/v1/foods/search"
    table = []
    index = 0
    for ingridient in ingridients:
        index += 1
        print (f"{index} from {len(ingridients)}")
        params = {
        'api_key' :get_api_key(),
        'query' : ingridient,
        'pageSize' : 1}
        time.sleep(0.5)
        try:
            response = requests.get(url, params=params, timeout=10)
            if response.status_code != 200:
                print(f'Error {response.status_code}')
                continue
        except:
            print ('error')
        if response.status_code == 200:
            data = response.json()
            row = {"name" : ingridient}
            if data.get('foods') and len(data['foods']) > 0:
                for i in data['foods'][0]['foodNutrients']:
                    row[i['nutrientName']] = i['value']
                table.append(row)
            else:
                table.append({'name': ingridient})
    if table:
        all_columns = set()
        for row in table:
            all_columns.update(row.keys())
            other_columns = sorted([col for col in all_columns if col != 'name'])
            all_columns_ordered = ['name'] + other_columns
        
        with open('foodNutrients.csv', 'w', encoding='utf-8', newline='') as file:
            writer = csv.DictWriter(file, fieldnames=all_columns_ordered, quoting=csv.QUOTE_NONNUMERIC)
            writer.writeheader()
            writer.writerows(table)
    
    return table

In [ ]:
request_food(  ['almond', 'amaretto', 'anchovy', 'anise', 'apple', 'apple juice', 'apricot', 'artichoke', 'arugula', 'asian pear', 'asparagus', 'avocado', 'bacon', 'banana', 'barley', 'basil', 'bass', 'bean', 'beef', 'beef rib', 'beef shank', 'beef tenderloin', 'beer', 'beet', 'bell pepper', 'berry', 'biscuit', 'blackberry', 'blue cheese', 'blueberry', 'bok choy', 'bourbon', 'bran', 'brandy', 'bread', 'breadcrumbs', 'breakfast', 'brie', 'brine', 'brisket', 'broccoli', 'broccoli rabe', 'brown rice', 'brussel sprout', 'buffalo', 'bulgur', 'butter', 'buttermilk', 'butternut squash', 'butterscotch/caramel', 'cabbage', 'calvados', 'campari', 'candy', 'cantaloupe', 'capers', 'caraway', 'cardamom', 'carrot', 'cashew', 'cauliflower', 'caviar', 'celery', 'chambord', 'champagne', 'chard', 'chartreuse', 'cheddar', 'cherry', 'chestnut', 'chicken', 'chickpea', 'chile', 'chile pepper', 'chive', 'chocolate', 'cilantro', 'cinnamon', 'citrus', 'clam', 'clove', 'coconut', 'cod', 'coffee', 'cognac/armagnac', 'collard greens', 'coriander', 'corn', 'cornmeal', 'cottage cheese', 'couscous', 'crab', 'cranberry', 'cream cheese', 'créme de cacao', 'crêpe', 'cr��me de cacao', 'cuba', 'cucumber', 'cumin', 'currant', 'curry', 'custard', 'date', 'dill', 'dried fruit', 'duck', 'eau de vie', 'egg', 'egg nog', 'eggplant', 'endive', 'escarole', 'fennel', 'feta', 'fig', 'fish', 'fontina', 'fortified wine', 'frangelico', 'fruit', 'fruit juice', 'garlic', 'gin', 'ginger', 'goat cheese', 'goose', 'gouda', 'grand marnier', 'granola', 'grape', 'grapefruit', 'grappa', 'green bean', 'green onion/scallion', 'ground beef', 'ground lamb', 'guam', 'guava', 'haiti', 'halibut', 'ham', 'hazelnut', 'herb', 'hominy/cornmeal/masa', 'honey', 'honeydew', 'horseradish', 'hot drink', 'hot pepper', 'hummus', 'iced coffee', 'iced tea', 'jalapeño', 'jerusalem artichoke', 'jícama', 'kahlúa', 'kale', 'kirsch', 'kiwi', 'kumquat', 'lamb', 'lamb chop', 'lamb shank', 'leafy green', 'leek', 'legume', 'lemon', 'lemon juice', 'lemongrass', 'lentil', 'lettuce', 'lima bean', 'lime', 'lime juice', 'lingonberry', 'liqueur', 'lobster', 'lychee', 'macadamia nut', 'mango', 'maple syrup', 'margarita', 'marsala', 'marscarpone', 'marshmallow', 'martini', 'mayonnaise', 'melon', 'mezcal', 'midori', 'milk/cream', 'mint', 'molasses', 'monterey jack', 'mortar and pestle', 'mozzarella', 'mushroom', 'mussel', 'mustard', 'mustard greens', 'nectarine', 'noodle', 'nut', 'nutmeg', 'oat', 'oatmeal', 'octopus', 'okra', 'olive', 'onion', 'orange', 'oregano', 'orzo', 'oyster', 'papaya', 'paprika', 'parmesan', 'parsley', 'parsnip', 'passion fruit', 'pea', 'peach', 'peanut', 'peanut butter', 'pear', 'pecan', 'pepper', 'pernod', 'persimmon', 'phyllo/puff pastry dough', 'pine nut', 'pineapple', 'pistachio', 'plantain', 'plum', 'poach', 'poblano', 'pomegranate', 'pomegranate juice', 'poppy', 'pork', 'pork chop', 'pork rib', 'pork tenderloin', 'port', 'potato', 'prosciutto', 'prune', 'pumpkin', 'quail', 'quince', 'quinoa', 'rabbit', 'rack of lamb', 'radicchio', 'radish', 'raisin', 'raspberry', 'red wine', 'rhubarb', 'rice', 'ricotta', 'root vegetable', 'rosemary', 'rosé', 'rum', 'rutabaga', 'rye', 'saffron', 'sage', 'sake', 'salmon', 'sangria', 'sardine', 'scallop', 'seed', 'semolina', 'sesame', 'sesame oil', 'shallot', 'sherry', 'shrimp', 'snapper', 'sour cream', 'sourdough', 'soy', 'soy sauce', 'sparkling wine', 'spice', 'spinach', 'squash', 'squid', 'strawberry', 'sugar snap pea', 'sweet potato/yam', 'swiss cheese', 'swordfish', 'tamarind', 'tangerine', 'tapioca', 'tarragon', 'tea', 'tequila', 'thyme', 'tilapia', 'tomatillo', 'tomato', 'tortillas', 'tree nut', 'tree nut free', 'triple sec', 'tropical fruit', 'trout', 'tuna', 'turnip', 'vanilla', 'veal', 'venison', 'vermouth', 'vinegar', 'vodka', 'walnut', 'wasabi', 'watercress', 'watermelon', 'white wine', 'wild rice', 'windsor', 'yellow squash', 'yogurt', 'yuca', 'zucchini'] 
    )

In [ ]:

def process_nutrition_data(df):
    result = pd.DataFrame()
    simple_mapping = {
        'Protein': 'protein',
        'Carbohydrate, by difference': 'carbohydrat',
        'Total lipid (fat)': 'fat',
        'Iron, Fe': 'Fe',
        'Magnesium, Mg': 'Mg',
        'Sodium, Na': 'Na',
        'Potassium, K': 'K',
        'Calcium, Ca': 'Ca',
        'Zinc, Zn': 'Zn',
        'Selenium, Se': 'Se',
        'Chromium': 'Cr',
        'Iodine': 'I',
        'Vitamin C, total ascorbic acid': 'C',
        'Copper, Cu': 'Cu'
    }
    for old_name, new_name in simple_mapping.items():
        if old_name in df.columns:
            result[new_name] = df[old_name]
    d_columns = ['Vitamin D (D2 + D3)', 
                 'Vitamin D (D2 + D3), International Units',
                 'Vitamin D2 (ergocalciferol)',
                 'Vitamin D3 (cholecalciferol)']
    result['D'] = 0
    for col in d_columns:
        if col in df.columns:
            result['D'] = result['D'].fillna(0) + df[col].fillna(0)
        b12_columns = ['Vitamin B-12', 'Vitamin B-12, added']
    result['B12'] = 0
    for col in b12_columns:
        if col in df.columns:
            result['B12'] = result['B12'].fillna(0) + df[col].fillna(0)
    e_columns = ['Vitamin E (alpha-tocopherol)', 'Vitamin E, added']
    result['E'] = 0
    for col in e_columns:
        if col in df.columns:
            result['E'] = result['E'].fillna(0) + df[col].fillna(0)
    result['A'] = 0
    
    if 'Vitamin A, RAE' in df.columns:
        result['A'] = df['Vitamin A, RAE'].fillna(0)
    else:
        if 'Retinol' in df.columns:
            result['A'] = result['A'] + df['Retinol'].fillna(0)
        if 'Carotene, beta' in df.columns:
            result['A'] = result['A'] + df['Carotene, beta'].fillna(0) / 12
        if 'Carotene, alpha' in df.columns:
            result['A'] = result['A'] + df['Carotene, alpha'].fillna(0) / 24
        if 'Cryptoxanthin, beta' in df.columns:
            result['A'] = result['A'] + df['Cryptoxanthin, beta'].fillna(0) / 24
    k_columns = ['Vitamin K (phylloquinone)',
                 'Vitamin K (Dihydrophylloquinone)',
                 'Vitamin K (Menaquinone-4)']
    
    result['K'] = 0
    for col in k_columns:
        if col in df.columns:
            result['K'] = result['K'].fillna(0) + df[col].fillna(0)
    
    if 'name' in df.columns:
        result.insert(0, 'name', df['name'])
    
    return result

In [ ]:
df = pd.read_csv('foodNutrients.csv')
df_processed = process_nutrition_data(df)
df_processed.to_csv('nutrition_processed.csv', index=False, encoding='utf-8')

In [ ]:
norms = {
    'fat': 78,
    'carbohydrat': 275,
    'protein': 50,
    'Fe': 18,               
    'Mg': 420, 
    'Na': 2300,             
    'K': 4700,              
    'Ca': 1300,             
    'Zn': 11,               
    'Se': 55,              
    'Cu': 0.9,              
    # 'I': 150,                
    # 'Cr': 35,              
    'C': 90,              
    'D': 20,     
    'B12': 2.4,             
    'E': 15,      
    'A': 900,              
    'K': 120,
}

In [ ]:
df_persentage = pd.DataFrame(df_processed['name'])
for col, norm_val in norms.items():
    if col in df_processed.columns:
        df_persentage [col] = (round((df_processed[col]/norm_val)*100,0)).astype('Int64')

In [ ]:
df_persentage.to_csv('data/nutrition_with_percents.csv', index=False)

### URL

In [24]:
df = pd.read_csv('data/epi_r.csv', usecols=['title'])

df['url'] = ''

for i in range(len(df)):
    df.loc[i, 'url'] = f"https://www.epicurious.com/recipes/food/views/{df.loc[i, 'title'].lower().strip().replace(' ', '-').replace(',', '')}"


df

,title,url
0,"Lentil, Apple, and Turkey Wrap",https://www.epicurious.com/recipes/food/views/...
1,Boudin Blanc Terrine with Red Onion Confit,https://www.epicurious.com/recipes/food/views/...
2,Potato and Fennel Soup Hodge,https://www.epicurious.com/recipes/food/views/...
3,Mahi-Mahi in Tomato Olive Sauce,https://www.epicurious.com/recipes/food/views/...
4,Spinach Noodle Casserole,https://www.epicurious.com/recipes/food/views/...
...,...,...
20047,Parmesan Puffs,https://www.epicurious.com/recipes/food/views/...
20048,Artichoke and Parmesan Risotto,https://www.epicurious.com/recipes/food/views/...
20049,Turkey Cream Puff Pie,https://www.epicurious.com/recipes/food/views/...
20050,Snapper on Angel Hair with Citrus Cream,https://www.epicurious.com/recipes/food/views/...
20051,Baked Ham with Marmalade-Horseradish Glaze,https://www.epicurious.com/recipes/food/views/...

In [ ]:
main_df = pd.read_csv("data/epi_r.csv")

main_df.drop(columns=['url'], inplace=True)

main_df = pd.merge(main_df, df, on='title')

main_df

,title,rating,calories,protein,fat,sodium,#cakeweek,#wasteless,22-minute meals,3-ingredient recipes,...,yogurt,yonkers,yuca,zucchini,cookbooks,leftovers,snack,snack week,turkey,url
0,"Lentil, Apple, and Turkey Wrap",2.500,426.0,30.0,7.0,559.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,https://www.epicurious.com/recipes/food/views/...
1,Boudin Blanc Terrine with Red Onion Confit,4.375,403.0,18.0,23.0,1439.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://www.epicurious.com/recipes/food/views/...
2,Potato and Fennel Soup Hodge,3.750,165.0,6.0,7.0,165.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://www.epicurious.com/recipes/food/views/...
3,Mahi-Mahi in Tomato Olive Sauce,5.000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://www.epicurious.com/recipes/food/views/...
4,Spinach Noodle Casserole,3.125,547.0,20.0,32.0,452.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://www.epicurious.com/recipes/food/views/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27899,Parmesan Puffs,3.125,28.0,2.0,2.0,64.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://www.epicurious.com/recipes/food/views/...
27900,Artichoke and Parmesan Risotto,4.375,671.0,22.0,28.0,583.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://www.epicurious.com/recipes/food/views/...
27901,Turkey Cream Puff Pie,4.375,563.0,31.0,38.0,652.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,https://www.epicurious.com/recipes/food/views/...
27902,Snapper on Angel Hair with Citrus Cream,4.375,631.0,45.0,24.0,517.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://www.epicurious.com/recipes/food/views/...
27903,Baked Ham with Marmalade-Horseradish Glaze,4.375,560.0,73.0,10.0,3698.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,https://www.epicurious.com/recipes/food/views/...

In [27]:
main_df.to_csv("data/epi_r.csv")